build_README.md:
	touch README.md

README.txt:
echo "The title of this project is Guessing Game by TS" > README.md

date=$(date)

echo "#####" >>README.md


echo "Date: $date" >> README.md

echo "#####" >> README.md



line_count=$(wc -l guessinggame.sh)

echo "There are $line_count lines of code in guessinggame.sh, but many of them are extra lines of text so pure code falls within parameters." >> README.md 
